format = """
$directory\
[](fg:blue bg:sumi_ink4)\
([$git_branch$git_status](bg:sumi_ink4)[](fg:yellow bg:sumi_ink4))\
$docker_context\
$nodejs\
$bun\
$python\
$php\
$perl\
$rust\
$golang\
$ruby\
$package\
[](fg:sumi_ink4)\
\n$character
"""

right_format = """
$cmd_duration \
$username\
[](fg:wave_blue2)\
$time
"""

add_newline = true
palette = "kanagawa"

[palettes.kanagawa]
sumi_ink0 = "#16161D"
sumi_ink4 = "#2A2A37"
wave_blue2 = "#2D4F67"

[directory]
style = "fg:sumi_ink0 bg:blue bold"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " 󰌾 "
read_only_style = "fg:red bg:blue"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ""
style = "fg:blue bg:sumi_ink4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:white bg:sumi_ink4"
format = "([$all_status$ahead_behind ]($style))"

[docker_context]
style = "fg:cyan bg:sumi_ink4"
format = "[  $context ]($style)"

[nodejs]
style = "fg:green bg:sumi_ink4"
format = "[  $version ]($style)"

[bun]
style = "fg:white bg:sumi_ink4"
format = "[  $version ]($style)"

[python]
style = "fg:yellow bg:sumi_ink4"
format = "[  $version ]($style)"

[php]
style = "fg:purple bg:sumi_ink4"
format = "[  $version ]($style)"

[perl]
style = "fg:blue bg:sumi_ink4"
format = "[  $version ]($style)"

[rust]
style = "fg:red bg:sumi_ink4"
format = "[  $version ]($style)"

[golang]
style = "fg:cyan bg:sumi_ink4"
format = "[  $version ]($style)"

[ruby]
style = "fg:red bg:sumi_ink4"
format = "[  $version ]($style)"

[package]
disabled = true
style = "fg:yellow bg:sumi_ink4"
format = "[ 󰏗 $version ]($style)"

[aws]
disabled = true

[gcloud]
disabled = true

[character]
vimcmd_symbol = "[V](bold green)"

[cmd_duration]
min_time = 1
style = "fg:yellow"
format = "[$duration]($style)" 

[username]
disabled = false
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "

[time]
disabled = false
time_format = "%R" # hh:mm
style = "fg:white bg:wave_blue2"
format = "[  $time ]($style)"
